#ifndef btl_chunk_h
#define btl_chunk_h

#include "common.h"
#include "value.h"

typedef enum {
    OP_CONSTANT, OP_CONSTANT_LONG, OP_NIL, OP_TRUE, OP_FALSE, OP_POP, OP_POP_N,
    OP_GET_LOCAL, OP_SET_LOCAL, OP_GET_GLOBAL, OP_GET_GLOBAL_LONG, OP_DEFINE_GLOBAL, OP_DEFINE_GLOBAL_LONG,
    OP_SET_GLOBAL, OP_SET_GLOBAL_LONG, OP_GET_UPVALUE, OP_SET_UPVALUE, OP_GET_PROPERTY, OP_GET_PROPERTY_LONG,
    OP_SET_PROPERTY, OP_SET_PROPERTY_LONG, OP_GET_SUPER, OP_GET_SUPER_LONG, OP_EQUAL, OP_GREATER, OP_LESS,
    OP_ADD, OP_SUBTRACT, OP_MULTIPLY, OP_DIVIDE, OP_MODULO, OP_NOT, OP_NEGATE,
    OP_PRINT, OP_JUMP, OP_JUMP_IF_FALSE, OP_LOOP,
    OP_CALL_0, OP_CALL_1, OP_CALL_2, OP_CALL_3, OP_CALL_4,
    OP_CALL_5, OP_CALL_6, OP_CALL_7, OP_CALL_8, OP_CALL,
    OP_TAIL_CALL_0, OP_TAIL_CALL_1, OP_TAIL_CALL_2, OP_TAIL_CALL_3, OP_TAIL_CALL_4,
    OP_TAIL_CALL_5, OP_TAIL_CALL_6, OP_TAIL_CALL_7, OP_TAIL_CALL_8, OP_TAIL_CALL,
    OP_INVOKE_0, OP_INVOKE_1, OP_INVOKE_2, OP_INVOKE_3, OP_INVOKE_4,
    OP_INVOKE_5, OP_INVOKE_6, OP_INVOKE_7, OP_INVOKE_8,
    OP_TAIL_INVOKE_0, OP_TAIL_INVOKE_1, OP_TAIL_INVOKE_2, OP_TAIL_INVOKE_3, OP_TAIL_INVOKE_4,
    OP_TAIL_INVOKE_5, OP_TAIL_INVOKE_6, OP_TAIL_INVOKE_7, OP_TAIL_INVOKE_8, OP_INVOKE,
    OP_INVOKE_LONG, OP_TAIL_INVOKE, OP_TAIL_INVOKE_LONG,
    OP_SUPER_INVOKE_0, OP_SUPER_INVOKE_1, OP_SUPER_INVOKE_2, OP_SUPER_INVOKE_3, OP_SUPER_INVOKE_4,
    OP_SUPER_INVOKE_5, OP_SUPER_INVOKE_6, OP_SUPER_INVOKE_7, OP_SUPER_INVOKE_8,
    OP_TAIL_SUPER_INVOKE_0, OP_TAIL_SUPER_INVOKE_1, OP_TAIL_SUPER_INVOKE_2, OP_TAIL_SUPER_INVOKE_3, OP_TAIL_SUPER_INVOKE_4,
    OP_TAIL_SUPER_INVOKE_5, OP_TAIL_SUPER_INVOKE_6, OP_TAIL_SUPER_INVOKE_7, OP_TAIL_SUPER_INVOKE_8, OP_SUPER_INVOKE,
    OP_SUPER_INVOKE_LONG, OP_TAIL_SUPER_INVOKE, OP_TAIL_SUPER_INVOKE_LONG,
    OP_CLOSURE, OP_CLOSURE_LONG, OP_CLOSE_UPVALUE, OP_RETURN,
    OP_CLASS, OP_CLASS_LONG, OP_INHERIT, OP_METHOD, OP_METHOD_LONG,
    OP_BUILD_LIST, OP_INDEX_GET, OP_INDEX_SET, OP_IMPORT, OP_IMPORT_LONG
} OpCode;

typedef struct {
    int count;
    int capacity;
    uint8_t* code;
    int* lines;
    ValueArray constants;
} Chunk;

void initChunk(Chunk* chunk);
void freeChunk(struct VM* vm, Chunk* chunk);
void writeChunk(struct VM* vm, Chunk* chunk, uint8_t byte, int line);
int addConstant(struct VM* vm, Chunk* chunk, Value value);

#endif